### ISSUE TITLE
Timer too fast

### ISSUE THREAD

**Issue by Akotosh** [Gorea235/TaledensInvManagerUpdated#2]
With the recent patch the timer seems to be running through the script really fast. It seems to be running the script several times a second causing severe lag on my server.

**Comment by Akotosh** [comment]
that did help but is there a way to make it bit more slower? Say if i add UpdateFrequency.Update150 - update every 150 ticks would that be valid?

**Comment by pckroon** [comment]
If I recall correctly SE only allows 1, 10 and 100.

**Comment by Gorea235** [comment]
That is correct, SE only allows for update frequencies of 1, 10 and 100. You will have to set all of the scripts individually and then recompile. Have you double checked this?

**Comment by Gorea235** [comment]
I've adjusted the default UpdateFrequency to 100 ticks, however I have added real-time-base udpate support which will be coming in v1.7.3, so you can optionally set the update frequency to every 1 or 2 seconds. I think this will solve any update issues you may have if you use a long enough update time (e.g. 2 seconds).

Keep in mind that I still limit the overall execution per call to about 35ms (might increase it further), so if TIM is running a bit slow, you might want to increase that (although if you increase it too much, each call will cause a lag spike, nullifying the benefits of the split calls)

**Comment by Gorea235** [comment]
Oh, as of v1.7.3 this is fixed, so it should no longer be an issue
