### ISSUE TITLE
New error after last patch

### ISSUE THREAD

**Issue by K1ll3rM** [Gorea235/TaledensInvManagerUpdated#20]
A new error occurred with the latest patch so I though I would make an issue for it here. It prevents it from compiling so it is definitely top priority.

Error:
The type or member 'string MyObjectBuilder_base.SubtypeName' is prohibited

**Comment by Gorea235** [comment]
I need to fully bring myself up to date with everything (cause of my silence, I will explain stuff soon), but I will need to look into this quickly. If I get proper internet tomorrow, I will spend this weekend working on all the updates for this script.

**Comment by K1ll3rM** [comment]
I would've done it myself if there was some good documentation on in-game scripting but I couldn't find any

**Comment by squirrelboot** [comment]
I think the errors are quite easy to fix, but someone with knowledge of the scripting language needs to do it. Essentially the error I see is: [this error](https://i.imgur.com/jSyxTcj.png)

People are suggesting the simple fix is changing the SubtypeName.ToString() to SubtypeId.ToString().
I'm no expert though. Just giving you an update.

**Comment by K1ll3rM** [comment]
@squirrelboot I will try this in game and update this when I find out if it works

**Comment by squirrelboot** [comment]
You should look at the pull request here. It's more specific about what needs to be changed and where: 

[Recent pull request](https://github.com/Gorea235/TaledensInvManagerUpdated/pull/21/commits/77b99261b1628cfe354918f67af1330575342d08)

**Comment by K1ll3rM** [comment]
@squirrelboot THat's not gonna help much if I need to minify it again :P

**Comment by Gorea235** [comment]
Should have been fixed by #21
