### ISSUE TITLE
building on linux

### ISSUE THREAD

**Issue by Akuukis** [Gorea235/TaledensInvManagerUpdated#7]
I am using Debian, but keep also Windows around for gaming. I would like to try out this script. Is it possible to build this on Linux?

**Comment by Gorea235** [comment]
Unfortunately, the builder is compiled against the .NET Framework 4.5.2, meaning it's Windows only. I will look at moving it to .NET Core latest soon, however.

**Comment by Akuukis** [comment]
Thanks!
